apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: alt-groovy/bus
profiles:
  - name: local
    activation:
      - kubeContext: minikube
        command: dev,run

  - name: local-cluster
    activation:
      - kubeContext: minikube
        command: dev,run
    deploy:
      kubectl:
        manifests:
          - .skaffold/manifests/local-cluster*.yaml
    portForward:
      - resourceType: service
        resourceName: bus-service
        namespace: default
        port: 8081
        localPort: 8081

  - name: dependency-cache
    build:
      artifacts:
        - image: gradle/dependency-cached
          docker:
            dockerfile: .docker/Dockerfile-gradle-7.4.1-jdk11-alpine-dependency-cached
build:
  artifacts:
    - image: alt-groovy/bus
      docker:
        dockerfile: .docker/Dockerfile
deploy:
  kubectl:
    manifests:
      - .skaffold/manifests/local.yaml
portForward:
  - resourceType: pod
    resourceName: bus
    namespace: default
    port: 8080
    localPort: 8080