apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: alt-groovy/bus
profiles:
  - name: local
    activation:
      - kubeContext: minikube
        command: dev,run

build:
  tagPolicy:
    gitCommit: { }
  artifacts:
    - image: alt-groovy/bus
      docker:
        dockerfile: .docker/Dockerfile
deploy:
  kubectl:
    manifests:
      - .skaffold/manifests/local.yaml
portForward:
  - resourceType: pod
    resourceName: bus
    namespace: default
    port: 9091
    localPort: 9091