apiVersion: v1
kind: Pod
metadata:
  name: bus
spec:
  containers:
    - name: bus
      image: alt-groovy/bus
      command: ["java","-jar","-Dspring.profiles.active=default","/app/bus-1.0.0.jar"]
      ports:
        - containerPort: 8080