apiVersion: v1
kind: Service
metadata:
  name: bus-service
spec:
  selector:
    app: bus-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
    - protocol: TCP
      port: 8082
      targetPort: 8082
    - protocol: TCP
      port: 9017
      targetPort: 9017
    - protocol: TCP
      port: 9018
      targetPort: 9018
