io:
  github:
    alt_groovy:
      bus:
        schedules:
          enabled: false
        service:
            schedule:
              Heartbeat : '0+*+8-17+?+*+MON-SUN'
            label:
              group:
                System : 'Heartbeat'
            Heartbeat : 'log:io.github.alt_groovy.bus?level=INFO'
